parameters:
#    certificacion.example.class: Iniaf\Bundle\CertificacionBundle\Example

services:
#    certificacion.example:
#        class: %certificacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
